source "https://rubygems.org"

gem "fastlane"
gem 'dotenv'
gem 'mutex_m'
gem 'abbrev'
gem 'bigdecimal'
gem 'fastlane-plugin-connected', '~> 0.1.3'
gem 'json', '~> 2.7', '>= 2.7.2'
gem 'cocoapods'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
